create table if not exists public.spaces (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  join_code varchar(6) not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  nickname varchar(80) not null,
  school varchar(120) not null,
  major varchar(120) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_members_space_id on public.members(space_id);

create table if not exists public.artifact_groups (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  label varchar(200) not null,
  common_points text,
  differences text,
  notes text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_groups_space_id on public.artifact_groups(space_id);

create table if not exists public.artifacts (
  id bigint generated by default as identity primary key,
  space_id bigint not null references public.spaces(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  title varchar(200) not null,
  content text not null,
  tags text,
  embedding text,
  group_id bigint references public.artifact_groups(id) on delete set null,
  status varchar(20) not null default 'PENDING'
    check (status in ('PENDING', 'PROCESSING', 'READY', 'FAILED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_artifacts_space_id on public.artifacts(space_id);
create index if not exists idx_artifacts_group_id on public.artifacts(group_id);

alter table public.spaces replica identity full;
alter table public.members replica identity full;
alter table public.artifacts replica identity full;
alter table public.artifact_groups replica identity full;

alter table public.spaces enable row level security;
alter table public.members enable row level security;
alter table public.artifacts enable row level security;
alter table public.artifact_groups enable row level security;

drop policy if exists spaces_select on public.spaces;
drop policy if exists members_select on public.members;
drop policy if exists artifacts_select on public.artifacts;
drop policy if exists artifact_groups_select on public.artifact_groups;

create policy spaces_select on public.spaces
  for select to anon, authenticated using (true);
create policy members_select on public.members
  for select to anon, authenticated using (true);
create policy artifacts_select on public.artifacts
  for select to anon, authenticated using (true);
create policy artifact_groups_select on public.artifact_groups
  for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on public.spaces, public.members, public.artifacts, public.artifact_groups
  to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.spaces;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.members;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.artifacts;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.artifact_groups;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;
